service: auction-service

provider:
  name: aws
  runtime: nodejs20.x
  profile: codecommit
  stage: ${opt:stage, 'dev'}

functions:
  createAuction:
    handler: src/handlers/createAuction.handler
    events:
      - httpApi:
          method: POST
          path: /auction
