service: auction-service

provider:
  name: aws
  runtime: nodejs20.x
  profile: codecommit
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: us-east-2
  environment:
    AUCTIONS_TABLE_NAME: ${self:custom.AuctionsTable.name}

resources:
  Resources:
    AuctionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: AuctionsTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: status
            AttributeType: S
          - AttributeName: endingAt
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: statusAndEndDate
            KeySchema:
              - AttributeName: status
                KeyType: HASH
              - AttributeName: endingAt
                KeyType: RANGE
            Projection:
              ProjectionType: ALL

functions:
  createAuction:
    handler: src/handlers/createAuction.handler
    events:
      - httpApi:
          method: post
          path: /auction
  readAuctions:
    handler: src/handlers/readAuctions.handler
    events:
      - httpApi:
          method: get
          path: /auction
  readAuction:
    handler: src/handlers/readAuction.handler
    events:
      - httpApi:
          method: get
          path: /auction/{id}
  updateAuction:
    handler: src/handlers/updateAuction.handler
    events:
      - httpApi:
          method: put
          path: /auction/{id}
  deleteAuction:
    handler: src/handlers/deleteAuction.handler
    events:
      - httpApi:
          method: delete
          path: /auction/{id}

  placeBid:
    handler: src/handlers/placeBid.handler
    events:
      - httpApi:
          method: patch
          path: /auction/{id}/bid

  processAuctions:
    handler: src/handlers/processAuctions.handler
    events:
      - schedule: rate(1 minute)

custom:
  AuctionsTable:
    name: AuctionsTable