service: hello-world

provider:
  name: aws
  runtime: nodejs20.x
  profile: codecommit
  stage: ${opt:stage, 'dev'}

functions:
  hello:
    handler: src/handlers/hello
    events:
      - httpApi:
          path: /
          method: get
